name:                alfred-footman
version:             0.1.0.0
github:              "meck/alfred-footman"
license:             BSD3
author:              "Johan Eklund"
maintainer:          "johan@meck.se"
copyright:           "Johan Eklund"

extra-source-files:
- README.md
- ChangeLog.md
- TODO.md

description:         A library for <http://www.alfredapp.com> to help writing script actions, providing helpers and persistent state

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - containers
  - bytestring
  - transformers
  - directory
  - lifted-base


executables:
  footman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alfred-footman
    - containers
    - utf8-string
    - time
    - strict
